name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GOOGLE_PROJECT }}/gcp-flask-demo

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy gcp-flask-demo \
            --image gcr.io/${{ secrets.GOOGLE_PROJECT }}/gcp-flask-demo \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated


            us-central1-docker.pkg.dev/wordpress-test-project-429717/gcp-flask-demo
