name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Container Registry
        run: echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GOOGLE_PROJECT }}/my-app:latest .
          docker push gcr.io/${{ secrets.GOOGLE_PROJECT }}/my-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: "latest"
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy with Docker Compose
        run: |
          gcloud compute instances create-with-container my-instance \
            --container-image=gcr.io/${{ secrets.GOOGLE_PROJECT }}/my-app:latest \
            --tags=http-server \
            --zone=us-central1-a
